### ISSUE TITLE
Release 3.2.0

### ISSUE THREAD

**Issue by NickNaso** [NickNaso/ghostscript4js#51]
The release `3.2.0` will contains updates to solve the following issues:
- [x] Segmentation fault on multiple runs - Fix issue [#47](https://github.com/NickNaso/ghostscript4js/issues/47)
- [x] Execution stop with: double free or corruption - Fix issue [#49](https://github.com/NickNaso/ghostscript4js/issues/49)
- [x] Error when calling gs.executeSync - Fix issue [#50](https://github.com/NickNaso/ghostscript4js/issues/50)

**Comment by NickNaso** [comment]
I'm closing the issue because the version `v3.2.0` has been released.
